# Generated by Django 4.1.6 on 2024-05-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pumaguaAPP', '0002_bebederos_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebederos',
            name='disponibilidad',
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('bebedero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pumaguaAPP.bebederos')),
            ],
        ),
    ]
